### PR TITLE
Fix for preflight allowed methods bug when multiple functions have the same path

### LINKED ISSUE #42: CORS broken for endpoints with the same path but different HTTP method
# This is a Bug Report

## Description

For bug reports:
* Preflight requests only return allowed methods for `OPTIONS` and the method of the first function in the serverless.yml with a given route **BUT NOT ANY AFTER THAT**
* If I have three functions with the following http events
    1. `POST /mypath`
    2. `PUT /mypath`
    3. `GET /mypath`
    Then the request `OPTIONS /mypath` should return this header `Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT`

* An example config which causes this bug to occur would be
```
Functions:
  questionSubmit:
    handler: src/index.questionCreate
    events:
      - http:
          integration: lambda
          path: forum/question
          method: post
          cors: true

  questionUpdate:
    handler: src/index.questionUpdate
    events:
      - http:
          integration: lambda
          path: forum/question
          method: put
          cors: true
```

### PR DESCRIPTION
**Pull request by rlgod**
## What did you implement:

Closes #42 

## How did you implement it:

This should definitely be rethought in the future but I basically collect a mapping of paths to allowed methods (based on the function http event methods) and then I hotswap those methods into the endpoints in the middleware when a preflight request comes in.

## How can we verify it:

Examples:
* serverless.yml
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          cors: true
  
  helloUpdate:
    handler: handler.helloUpdate
    events:
      - http:
          path: hello
          method: put
          cors: true
```
* Screenshots
### Master: 
screen shot 2017-03-11 at 7 08 05 pm
### This fix: 
screen shot 2017-03-11 at 7 08 17 pm

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

## Notes:
I also noticed while touching this code that there might be some interesting behaviour when different cors origins are explicitly defined between different functions (not sure if serverless catches this issue before it gets to the plugin or not) 

***Is this ready for review?:*** YES

### CODE REVIEW

File: lib/config.js [hunk 1]
```diff
@@ -201,18 +201,38 @@ const getFunction = (serverless, name) =>
...
     const func = functions[name]
     if (!func.events) return accum
 
     const events = func.events.filter(event => 'http' in event).map(event => {
       const http = getHttpConfig(functions, event.http)
       const config = Object.assign({}, func.config, { http })
+
+      if (http.cors && http.cors.methods) {
+        if (corsMethodsForPath[http.path]) {
+          http.cors.methods.forEach((val) => {
```
Comment (gertjvr) [inline lib/config.js]: Not that you need to change it, but try replacing forEach with either a map or reduce function.

File: lib/config.js [hunk 2]
```diff
@@ -201,18 +201,39 @@ const getFunction = (serverless, name) =>
 const getEndpoints = (serverless) => {
   const functions = getFunctions(serverless)
 
-  return Object.keys(functions).reduce((accum, name) => {
+  let corsMethodsForPath = {}
```
Comment (johncmckim) [inline lib/config.js]: Instead of doing this outside, could you use an object in the reducer to return the entire config you need. i.e. 

```js
const config = Object.keys(functions).reduce((accum, name) => {
  accum.endpoints.push(xxx)
  accum.corsEndpoints[xxx] = yyy;
}, {
  endpoints: [],
  corsEndpoints: {
  }
})
```

**Comment by rlgod** [comment]
How's that @johncmckim. I fear I still haven't really done it that well but maybe merge worthy

**Comment by johncmckim** [comment]
I'd prefer better test coverage. But let's get it in. You can fix it if it breaks 😃
